### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by theartcher** [theartcher/Trash4Cash#1]
- [ ] Work on integration to a live database for the project
- [ ] Add more screens
- [ ] Add a functional login page
- [ ] NFC integration
